### PR TITLE
add piyush biswal

### PR DESCRIPTION
**Pull request by piyush-repo**
I would like to register for JS CraftCamp.

- [ ] My pull request contains a JSON file `$name_or_nickname.json`
- [ ] The JSON file follows the template at [https://github.com/jscraftcamp/website/blob/main/participants/\_template.json](https://jscraftcamp.org/register/) and contains the mandatory fields like `name`, `when`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`
- [ ] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ ] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on GitHub and I agree that I will be listed on the JSCraftCamp website as a participant.
- [ ] I agree that photos and videos might be taken and published (e.g. on social media) during the event.
- [ ] I understand that I might NOT get a T-Shirt, because they might be in production already
- [ ] I asked my company about sponsoring (see open items at: https://github.com/orgs/jscraftcamp/projects/5/views/1)

Are you from a sponsoring company?

- [ ] Yes, I am from company ?????

### CODE REVIEW

**Comment by meldron** [comment]
Hi @piyush-repo, glad having you for the bar camp. Feel free to join us on [Discord](https://discord.gg/3mHhaXVEjP) too.

**Comment by Narigo** [comment]
Hey @piyush-repo - glad to see someone from Jochen Schweizer / mydays again!

Could you please make sure to tick the checkboxes from the PR template? We want to make sure everybody has read those and is okay with these.

Please reach out if you have any questions (either here or through the [JSCC Discord](https://discord.gg/3mHhaXVEjP))!

**Comment by piyush-repo** [comment]
I have checked in all the check boxes.

**Comment by Narigo** [comment]
Thanks a lot @piyush-repo ! Happy to meet you at the JSCC 🙂

**Pull request merged**
