### PR TITLE
A completely unstyled, non-interactive tag cloud ... input welcome

### PR DESCRIPTION
**Pull request by wolframkriesing**
This shows an ugly tag cloud. Any further ideas and improvements welcome.
Looks like this, currently :(

bildschirmfoto 2016-09-17 um 19 10 20

### CODE REVIEW

**Comment by marcoemrich** [comment]
I like so far. One Idea:

maybe have more diverse font-sizes in the less "than 8"-area.

Instead of
 var fontSize = count < 8 ? 8 : ( count > 30 ? 30 : count );

Maybe something like this:

 var fontSize = (count + 8) > 30 ? 30 : 8 + count);

I will make PR if you like the idea...

**Comment by marcoemrich** [comment]
also a table for synonyms like angularjs, angular.js, angluar, etc.

**Comment by wolframkriesing** [comment]
feel free to adjust anything you like

Saludos, Regards, Gruesse

Wolfram Kriesing
crafting away software

JSCraftCamp, Munich, 8th+9th October <http://jscraftcamp.org>

2016-09-19 14:17 GMT+02:00 Marco Emrich <notifications@github.com>:

**Comment by wolframkriesing** [comment]
too old to be relevant

**Pull request closed without merging**
