### PR TITLE
small styling improvements

### PR DESCRIPTION
**Pull request by marcoemrich**
Add class flow-text (from materialize design) to most text elements (p-Tags).

 *  some of the text have been too small, hard to read.
 *  this also helps with consistency, because it now uses the correct font (Roboto) from materialze design
 * the class is designed with moible in mind and scales down as fit.

Also made some minor improvements to the imprint page

### CODE REVIEW

**Comment by davelosert** [comment]
I like it! :+1: 
One minor thing though: Imho, the text on the index page is very large now on desktop devices. Is there a way to reduce the font size a little bit? Else it takes up a lot of room...

**Comment by marcoemrich** [comment]
sure, we can overwrite the style...

**Comment by wolframkriesing** [comment]
if you want to fix that feel free, otherwise we can merge it imho

**Comment by marcoemrich** [comment]
should be fixed. Did I miss something?

**Pull request merged**
