### PR TITLE
Added Anna Gruber as a participant

### PR DESCRIPTION
**Pull request by futuranna**
I would like to register for JS CraftCamp.    
- [x] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [x] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.

### CODE REVIEW

**Comment by wolframkriesing** [comment]
would you mind adding the `what_can_i_contribute` field in you JSON file? There is surely something you can contribute, from giving opinion, sharing, presenting or even running a session ... thanks in advance

**Comment by lowsky** [comment]
Hi Anna (@futuranna) would you have a moment and would like to add that little info into your registration.
I am pretty sure you will have a lot you could contribute.

I am looking forward to have you there!

**Comment by futuranna** [comment]
Please help me out here. I don't quite understand what I am supposed to do.

**Comment by wolframkriesing** [comment]
all done, thanks @futuranna ... you already added the `what_can_i_contribute`, yeah!!! see you there

**Pull request merged**
