### PR TITLE
Create carlos_wimmer.json

### PR DESCRIPTION
**Pull request by carloswimmer**
I would like to register for JS CraftCamp.

- [x] My pull request contains a JSON file `$name_or_nickname.json`
- [x] The JSON file follows the template at [https://github.com/jscraftcamp/website/blob/main/participants/\_template.json](https://jscraftcamp.org/register/) and contains the mandatory fields like `name`, `when`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`
- [x] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on GitHub and I agree that I will be listed on the JSCraftCamp website as a participant.
- [x] I agree that photos and videos might be taken and published (e.g. on social media) during the event.
- [x] I understand that I might NOT get a T-Shirt, because they might be in production already
- [ ] I asked my company about sponsoring (see open items at: https://github.com/orgs/jscraftcamp/projects/5/views/1)

Are you from a sponsoring company?

- [ ] Yes, I am from company ?????

### CODE REVIEW

**Comment by Narigo** [comment]
Hi and welcome @carloswimmer ! Do you mind adding some tags that reflect more on what you're working with? Also maybe introduce yourself a bit in the `whatCanIContribute` so other people are able to tell what sessions you may like or participate in.

For example, just based on your repositories, I could imagine tags like: `["React", "ReactNative", "Typeorm", "TypeScript"]` - the contribution could be something about your relationship to the bootcamp you did there or maybe something about how to create pleasant frontend experiences.

**Comment by Narigo** [comment]
Oh and if you need help with that, feel free to join [the JSCC Discord](https://discord.gg/3mHhaXVEjP) there are lots of helpful people in there 😅

**Comment by carloswimmer** [comment]
Sure, I will include more tags there. Thank you for the hints.

**Comment by carloswimmer** [comment]
And, it can sound lazy but, my tags are exactly what you mention 😄

**Pull request merged**
