### PR TITLE
patrick is participating

### PR DESCRIPTION
**Pull request by floatec**
I would like to register for JS CraftCamp.    
- [x] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute_to_js_craftcamp`    
- [x] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org

### CODE REVIEW

**Comment by cko** [comment]
Would be cool if you could provide a smaller version of your photo as the links are directly included in the website.

**Comment by floatec** [comment]
what is the correct size?

**Comment by cko** [comment]
smaller than 200k

**Comment by cko** [comment]
The photo is not mandatory you can also just remove it.

**Comment by wolframkriesing** [comment]
was outstanding for too long, reopen if really interested to come

**Pull request closed without merging**
