### PR TITLE
add Frank Blendinger to participants

### PR DESCRIPTION
**Pull request by yogan**
I would like to register for JS CraftCamp.    
- [x] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [x] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org

### CODE REVIEW

**Comment by davelosert** [comment]
@yogan : Thanks for your registration.

I'd be happy to attend a *VIM* Session. Using it myself since a few months and what can I say? I love it! 
would be great to hear your experiences and get some tips! I am looking forward on talking with you about it on JSCC17!

**Comment by yogan** [comment]
@davelosert Sure, I love talking about Vim. Do you have any special topics you're interested in? Vim is so powerful, and nobody knows everything. I can give a session on the basics (movements, modes, buffers, search/replace, etc.), or more advanced topics like registers, macros, and plugins. When I know what is of most interest, I can prepare accordingly.

**Comment by davelosert** [comment]
@yogan : I'd say that also depends on the interest of other participants. Going with basics is for sure not a bad idea as I know a lot of people don't really like vim. I'd even visit a more advanced session as well :)

So imho, I'd say prepare the basics and lets improvise together if the interest arises! :smile:

**Comment by yogan** [comment]
@davelosert That sound good, thanks for the input.

**Pull request merged**
