### PR TITLE
just a fix to a problem i had, please review

### PR DESCRIPTION
**Pull request by a7madgamal**
I would like to register for JS CraftCamp.    
- [ ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`  
- [ ] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`  
- [ ] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org

### CODE REVIEW

**Comment by wolframkriesing** [comment]
@a7madgamal could it not also just be added to the package.json, e.g. via `npm install harp@next --save`?

**Comment by a7madgamal** [comment]
@wolframkriesing tbh I was super busy at work to look into it. I assumed a big issue like this is related to my machine or setup so wasn't sure why did it happen (i don't even know what harp is :D )
if other people confirm this issue I can add it to package.json for sure

**Comment by wolframkriesing** [comment]
no big deal, we can do a session on it tomorrow analyze and fix it :)

**Comment by davelosert** [comment]
@a7madgamal You were on a linux machine? My build failed as well due to a bug in harp 0.20.x - I updated it within #173 - maybe try again. Then we could close this issue.

**Comment by a7madgamal** [comment]
nope. a mac
will try again at Monday

**Comment by davelosert** [comment]
I updated harp and this error seems to be resolved by it. Therefore I will close this without merging.
Still thanks a lot @a7madgamal for your effort! :+1:  :)

**Pull request closed without merging**
