### PR TITLE
Mobile improvements

### PR DESCRIPTION
**Pull request by wolframkriesing**
- [x] adjust the font-sizes for better readability
- [x] center the subscribe form
- [x] center the logo on mobile and
- [x] animate logo to fixed top right when user scrolls 

See screens below

before:
old font sizes

after:
bildschirmfoto 2017-04-17 um 00 00 57

### CODE REVIEW

**Comment by davelosert** [comment]
It looks very cool, and I like the animation.

One minor thing: When scrolling down (after the animation) and up again, the logo doesn't return to it's original position, see here:
https://slack-files.com/T44KKGN4X-F50PW8HPY-f3aacdc418

Tested on a Samsung S6 on Chrome.

**Comment by wolframkriesing** [comment]
yep I know, no idea what to do about it though.
Shall we put it back to the middle position?

Saludos, Regards, Gruesse

Wolfram Kriesing


… about crafting (and) JavaScript http://picostitch.com

2017-04-17 18:02 GMT+02:00 David Losert <notifications@github.com>:

**Comment by wolframkriesing** [comment]
now @davelosert must like it :)

**Comment by davelosert** [comment]
@wolframkriesing : Sorry this comes late - its really great now. Awesome work! :D

**Pull request merged**
