### PR TITLE
Create robert.json

### PR DESCRIPTION
**Pull request by spock111**
I would like to register for JS CraftCamp.    
- [ x] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute_to_js_craftcamp`    
- [x] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org

### CODE REVIEW

**Comment by cko** [comment]
please read+check the boxes in the PR text, thanks

**Comment by spock111** [comment]
ok

**Comment by davelosert** [comment]
Do you have anything to share with us or at the conference? Would be nice to know what you'd like - via tags or what you can contribute. Maybe you can add in a little more? Would be great :+1:

**Comment by cko** [comment]
We will probably be booked out in a few days. Please add the missing information as soon as possible otherwise you might not get a seat.

**Comment by spock111** [comment]
added

**Comment by cko** [comment]
Still not that detailled. 
btw maybe  https://www.meetup.com/de-DE/nodeschool-augsburg/events/233116101/ is interesting for you?

**Comment by lowsky** [comment]
No clue, who you are:
spock111 ? 
http://strekonline.com/31005/star-trek-movie-screencaps/star-trek-iii-the-search-for-spock/attachment/star-trek-iii-the-search-for-spock-111

So somebody who's name is Robert will get a Large T-shirt, tomorrow.

I am curious. CU :-)

**Pull request merged**
