### PR TITLE
chore: add dgrabla as participant

### PR DESCRIPTION
**Pull request by dgrabla**
I would like to register for JS CraftCamp.

- [X] My pull request contains a JSON file `$name_or_nickname.json`
- [X] The JSON file follows the template at [https://github.com/jscraftcamp/website/blob/main/participants/\_template.json](https://jscraftcamp.org/register/) and contains the mandatory fields like `name`, `when`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`
- [X] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [X] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on GitHub and I agree that I will be listed on the JSCraftCamp website as a participant.
- [X] I agree that photos and videos might be taken and published (e.g. on social media) during the event.
- [X] I understand that I might NOT get a T-Shirt, because they might be in production already
- [X] I asked my company about sponsoring (see open items at: https://github.com/orgs/jscraftcamp/projects/5/views/1)

Are you from a sponsoring company?

- [ ] Yes, I am from company

### CODE REVIEW

**Comment by meldron** [comment]
Hey @dgrabla, nice having you!

**Comment by Narigo** [comment]
Welcome David! Just a quick question: Are you sure about the "only Saturday" setting?
(I'm asking this everybody where I see only one day being set as I want to make sure no one does this by accident 😉)

**Comment by dgrabla** [comment]
@Narigo Yeah I cannot make it on Friday, I hope there is some fun left for the Saturday people

**Comment by Narigo** [comment]
I'm sure Saturday will be lots of fun as well 😄

Btw, are you a freelancer? Because of the company name === your name 😅

**Comment by dgrabla** [comment]
Yeah I'm a freelancer and at the moment I invoice clients directly on my name, I don't own a UG/gmbh etc.  
I was not sure what should I write as company. I checked all committed participants and all had a company. Should I put an empty string instead?

**Comment by Narigo** [comment]
I'd say whatever you like to have on your participants card :) I've seen someone else writing "Freelancer" on it

**Pull request merged**
