### PR TITLE
waiting list: Add Friday for Florian

### PR DESCRIPTION
**Pull request by fgeierst**
This is a follow up PR to add myself on the Friday waiting list.

- [x] My pull request contains a JSON file `$name_or_nickname.json`
- [x] The JSON file follows the template at [https://github.com/jscraftcamp/website/blob/main/participants/\_template.json](https://jscraftcamp.org/register/) and contains the mandatory fields like `name`, `when`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`
- [x] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on GitHub and I agree that I will be listed on the JSCraftCamp website as a participant.
- [x] I agree that photos and videos might be taken and published (e.g. on social media) during the event.
- [x] I understand that I might NOT get a T-Shirt, because they might be in production already
- [ ] I asked my company about sponsoring (see open items at: https://github.com/orgs/jscraftcamp/projects/5/views/1)

Are you from a sponsoring company?

- [ ] Yes, I am from company ?????

### CODE REVIEW

**Comment by Narigo** [comment]
Can you resolve the merge conflict please?

**Comment by fgeierst** [comment]
Merge conflict is resolved.

**Comment by Narigo** [comment]
> Merge conflict is resolved.

Thanks a lot! You're on the waitlist for Friday now and have a safe spot for Saturday 👍

**Comment by Narigo** [comment]
We've been merging the open PRs now and you're in! Welcome to the JSCC23 again and looking forward to seeing you on Friday as well!

**Pull request merged**
