### PR TITLE
Add Tobias Gutmann to participants

### PR DESCRIPTION
**Pull request by Karl-Heinrich**
I would like to register for JS CraftCamp.    
- [x] My pull request contains a JSON file `$firstname_$lastname.json` or `$nickname.json`    
- [x] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [x] If I can't attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
- [x] I agree that photos and videos might be taken and published (e.g. on social media) during the event.

Are you from a sponsoring company?
- [x] Yes, I am from company [@methodpark](https://github.com/methodpark)

### CODE REVIEW

**Comment by wolframkriesing** [comment]
@Karl-Heinrich or Tobias Gutmann interesting mix of names, one nickname or both? :)

**Comment by wolframkriesing** [comment]
hi @Karl-Heinrich, we are closing this PR due to inactivity, if you still want to participate, please see our questions/requests above and act accordingly, so we can merge your PR. thanks

**Comment by Karl-Heinrich** [comment]
Hi @wolframkriesing could you please explain what went wrong? My name is `Tobias Karl-Heinrich Gutmann`. I am trying to register under my full name, `Tobias Gutmann`. What does any of this have to do with my Github username, which just happens to be my middle name? `Tobias Gutmann` is also set as my name for authoring commits.

**Comment by marcoemrich** [comment]
looks like a simple miss-understanding to me. Sorry for that

**Pull request merged**
