### PR TITLE
Add dnnr to participants

### PR DESCRIPTION
**Pull request by dnnr**
I would like to register for JS CraftCamp.

- [x] My pull request contains a JSON file `$name_or_nickname.json`
- [x] I read the `THE IMPORTANT STUFF` at [https://jscraftcamp.org/registration](https://jscraftcamp.org/registration), the JSON file follows the [template](https://github.com/jscraftcamp/website/blob/main/participants/_template.json), and contains the mandatory fields like `realName`, `githubAccountName`, `when`, `iCanTakeNotesDuringSessions`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`.
- [x] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on GitHub and I agree that I will be listed on the JSCraftCamp website as a participant.
- [x] I agree that photos and videos might be taken and published (e.g. on social media) during the event.
- [x] I understand that I might NOT get a T-Shirt, because they might be in production already
- [ ] I asked my company about sponsoring (see open items at: https://github.com/orgs/jscraftcamp/projects/5/views/1)

### CODE REVIEW

**Comment by wolframkriesing** [comment]
Welcome to the jscc, @dnnr may you have a look into the failing test of your PR. We need the tests to be green in order to merge and finish the registration.

**Comment by dnnr** [comment]
I've opened https://github.com/jscraftcamp/website/pull/1932 to address the issue. Hope that works.

**Comment by Narigo** [comment]
Hello there @dnnr!

I do appreciate the idea of relaxing the rules about names, but let me try to share you some context, so you can better understand the reasoning behind the current solution.

As you have read in `THE IMPORTANT STUFF` section, we need the **real names** of all the people attending. This is a requirement of the location. If we have someone not being able to put in their name due to the restrictive check we've set up, we expect them to reach out via e-mail. If someone forgets to set their name or sets it to something to stay anonymous, the current check that you want to change warns them about it. From past experiences, we expect those cases to happen way more often as people tend to not completely read the rules.

Personally, I'm fine with admitting people who do not want to share their real name on a website or in a git history. Doing so would make our processes internally a lot harder though as we won't be able to easily automate generating lists: For example, we need a list for the location with the names as mentioned and we also need the correct numbers of participants who have dietary requirements, who wants a t-shirt in what size, how many people will attend on which day, etc.

Having to track multiple people manually through this would be a lot of extra work for the orga team. We currently automate all of this through scripts that we can use thanks to the JSON files provided by the participants. This process is transparent to everybody. Introducing private databases and automations would involve a lot of extra work - not just scripting but also in terms of legal implications regarding data protection laws.

This is a _free_ conference and we want to keep it this way. We try to make this as accessible as we can for everybody. We do not receive money for creating this event and working on this community. I'm convinced that the sharing of knowledge, networking and caring about each other as well as the general vibe at the event only happens because of this being radically different from other conferences.

It's still a lot of work though. To be frank, it has been pretty hard to motivate enough people to organize this year, because it already meant a lot of work for each of us.

@meldron and me actually had a short discussion about the naming rules before we opened the registration and we decided to use this separate given and family name to be able to do the check as quickly as possible at the entrance. If someone puts in something else in the "real name" field, it will cause increased waiting times for everybody behind them during admission. We generally want to avoid this.

So I hope you can understand why we have more restrictive rules like this in place right now.

Now back to your registration: You do have a name on your GitHub profile, it shows up in notification e-mails and it does not match the one that you want to put into the pull request. I'm suspecting that "D" is not the real name that you can identify yourself with through a passport or similar means. If it is and you can provide an identification, please reach out via e-mail, let's discuss it during one of the next orga calls and let's make it possible for you to join the event.

If it's not your real name and you don't want to put it in here, please reach out through e-mail. Please keep in mind that creating and thinking about the phrasing of this wall of text in the middle of the night took me over 2.5 hours. Introducing a special process for you will take all of us even more time that we're not getting paid for... thanks!

**Comment by dnnr** [comment]
Thanks for the context! I did not intend for you to lose any sleep over this. And I appreciate your efforts in organizing this event. With that in mind, I'll change my PR. But I'd be delighted to see a more privacy-friendly approach implemented in the next iteration.

I'm sure it's not intentional, but you might miss out on people who have much stronger reasons rather not to follow the current process. For instance, what about somebody dealing with a stalker and not wanting to broadcast where they are going to be at a certain time? Or somebody who's in the process of changing their name who prefers not to publicly divulge their legacy name just because it's still on their passport?

And there's one particular point you've made that I'd like to respond to:

> You do have a name on your GitHub profile

I do. But I retain full control over my GitHub profile, which is something I cannot say about this repository, its currently 345 forks and all future forks.

**Pull request merged**
