### PR TITLE
Create basan_kuberlinov.json

### PR DESCRIPTION
**Pull request by KuBerlinOV**
Dear JSCraftCamp team,

I would be very thankful for the opportunity to join your barcamp! Thank you in advance.

Best,
Basan Kuberlinov

I would like to register for JS CraftCamp.

- [x] My pull request contains a JSON file `$name_or_nickname.json`
- [x] I read the `THE IMPORTANT STUFF` at [https://jscraftcamp.org/registration](https://jscraftcamp.org/registration), the JSON file follows the [template](https://github.com/jscraftcamp/website/blob/main/participants/_template.json), and contains the mandatory fields like `realName`, `githubAccountName`, `when`, `iCanTakeNotesDuringSessions`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`.
- [x] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on GitHub and I agree that I will be listed on the JSCraftCamp website as a participant.
- [x] I agree that photos and videos might be taken and published (e.g. on social media) during the event.
- [x] I understand that I might NOT get a T-Shirt, because they might be in production already
- [x] I asked my company about sponsoring (see open items at: https://github.com/orgs/jscraftcamp/projects/5/views/1)

Are you from a sponsoring company?

- [ ] Yes, I am from company ?????

### CODE REVIEW

**Comment by wolframkriesing** [comment]
hi @KuBerlinOV cool to see your interest in the JSCC.
Please make sure to read and tick off the according boxes in your PR text.
If you need any more help feel free to let us know.

**Comment by KuBerlinOV** [comment]
Hi Wolfram, I have just checked the boxes. I am not sure what should I do next? :)

**Comment by Narigo** [comment]
Hi @KuBerlinOV, great to see you joining us this year and meeting you in person! 🥳

There is an issue with the JSON still:
```
Invalid participant json 'participants/basan_kuberlinov.json':
	'githubAccountName': Required
	'tShirtSize': Invalid enum value. Expected 'S' | 'M' | 'L' | 'XL' | '2XL' | '3XL', received 'UNDEFINED'
	Unrecognized key(s) in object: 'tShirt'
```

It looks like you've used an older version of our template - instead of `tShirt` we only have `tShirtSize` and we require the `githubAccountName` field now.

**Comment by KuBerlinOV** [comment]
Hi @Narigo , thank you for the answer. I have made the changes in my json file, but now I stuck at the tests with the "test Expected — Waiting for status to be reported". Sorry, I did not have that much experience with GitHub actions and have to figure out on the go :)

**Comment by KuBerlinOV** [comment]
Ah, I understand, I thought these were just tests. Thank you! :)
I am looking forward to meeting you at the barcamp!

**Pull request merged**
