### PR TITLE
Say thanks and prepare a possible #jscc17

### PR DESCRIPTION
**Pull request by davelosert**
@wolframkriesing @marcoemrich @lujakob : I changed the page here a little to say thanks for #jscc16 and kind of announce a possible #jscc17.

I also raised the newsletter registration - I think we could use the existing newsletter system for people who are interested inthe next JSCraftCamp.

What do you guys think? Feedback welcome.

### CODE REVIEW

**Comment by marcoemrich** [comment]
Hi David,

I think would leave the schedule in. Maybe rename it to Schedule 2016. I think, when we are ready for announcing JSCC17, we want to have an "archive"-page with everything still in place.

On the other hand, we could also drop it now, and get it back later for the archive. I wouldn't mind to merge this. 

Anyway - excellent work. thanks!

**Comment by davelosert** [comment]
Hey @marcoemrich @wolframkriesing : First of all: Happy new Year! 

I would like to change our Website to kind of start preparing for a JSCC17 somewhat this year. If you guys are interested, we could also start talking about it starting next week. I am also going to send this via mail.

**Comment by marcoemrich** [comment]
sounds great! Maybe we want to have some kind of archive, where one can
look up the previous years.

**Comment by davelosert** [comment]
Closing in favor for #176

**Pull request closed without merging**
