### PR TITLE
feat: Add alumni page and move past orga members there

### LINKED ISSUE #1331: Add (Alumni, new) Organizers on the website
We wan't to separate the organizer page in two categories:

* current organizers
* alumni

### PR DESCRIPTION
**Pull request by Narigo**
To all reviewers: Please let me know if you want to remove picture, email or something like that.

There are a few new members here - I need pictures and e-mail addresses (if you want to put them on the page).

If you want me to add socials or anything else, please let me know. I wouldn't mind linking to portfolio pages or similar. Thanks to all the organizers and alumnis! :)

- Resolves #1331

### CODE REVIEW

**Comment by wolframkriesing** [comment]
2016 @cko was also part of the team you can also see her contributions on https://github.com/jscraftcamp/website/graphs/contributors not sure we have a pic, but maybe we can list her too

**Review by davelosert — APPROVED** [review]

**Comment by lowsky** [comment]
Nice design! I like the solution!

**Review by lowsky — APPROVED** [review]
LGTM

**Review by cowglow — APPROVED** [review]
Nicely done

**Comment by meldron** [comment]
What do you think about puttint the alumni on the same page, but in another section? Also let's link the team site in the main navigation

**Comment by Narigo** [comment]
> What do you think about puttint the alumni on the same page, but in another section? Also let's link the team site in the main navigation

I wanted to avoid confusion about the current and past team members, so I split it up into two pages. Especially after having people reach out to individual alumnis recently...

I put the team page link to the bottom as it was there in the past and I didn't think too much about this. Shall we change it? We could also do it in another PR

**Pull request merged**
