### PR TITLE
Added patrick_seebauer.json

### PR DESCRIPTION
**Pull request by P-Seebauer**
I would like to register for JS CraftCamp.    
- [x ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [x ] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [x ] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org

### CODE REVIEW

**Comment by cko** [comment]
We are booked out for saturday for now. You can either modify your registration and just participate on sunday or wait until next tuesday. We will probably add some more seats then.

**Comment by P-Seebauer** [comment]
Okay, I'll just wait till Tuesday and change my pull request then, if this isn't too much of an inconvenience.

**Comment by wolframkriesing** [comment]
you may also want to share a bit `what_can_i_contribute` with us? thanks

**Comment by wolframkriesing** [comment]
open for >20 days ... closing it

**Pull request closed without merging**
