### PR TITLE
added participant Vincent Wagner

### PR DESCRIPTION
**Pull request by serofax**
I would like to register for JS CraftCamp.    
- [x] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute_to_js_craftcamp`    
- [x] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org

### CODE REVIEW

**Comment by wolframkriesing** [comment]
you also have any car-specific topics that might be interesting? IoT+JS+Audi, etc? Would be awesome to hear some cool insights from how to auto-pilot an Audi with JavaScript :)

**Comment by serofax** [comment]
Sure :)

**Comment by wolframkriesing** [comment]
do you mind adding some in the `what_can_i_contribute` section in the JSON file ... sorry that I am so picky, I just would love to see some of it and maybe tweet it around :)
thanks

**Comment by serofax** [comment]
That is tricky because most of the stuff I know I'm not allowed to talk / write about. Stupid confidentiality ;).

To lower your expectations a little bit. I'm not in a department where the cool stuff is developed. I heard some stories from colleagues. In my team we using JS to build a webapp which runs in normal browser not in a car.

But I'll think about what I can improve an my page.

**Comment by wolframkriesing** [comment]
looking forward to having you on board, thanks for the time to chat with me :)

**Pull request merged**
