### PR TITLE
add Iwan

### PR DESCRIPTION
**Pull request by iwangu**
I would like to register for JS CraftCamp.    
- [ x] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [x ] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute_to_js_craftcamp`    
- [ x] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org

### CODE REVIEW

**Comment by cko** [comment]
Please prefix your urls with `http`, otherwise the build will fail.

**Comment by wolframkriesing** [comment]
could you please link a smaller image, it will be loaded as part of the page where all participants are shown, 1MB is quite big, thanks

**Comment by iwangu** [comment]
done.

**Comment by wolframkriesing** [comment]
what do you mean by "I can find you cool tech jobs in Zurich" ? (sounds recruiter style :) is it meant like that?)

**Pull request merged**
