### PR TITLE
register jonas_lorenz and daniel_glasemann

### PR DESCRIPTION
**Pull request by jonaslorenz**
I would like to register for JS CraftCamp.
- [x] My pull request contains TWO JSON files `$firstname_$lastname.json` or `$nickname.json`    
- [x] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` (the field what_can_i_contribute is not mandatory)
- [x] If I any of us can't attend, we will either send another pull request removing one or both of the JSON files or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x] We agree that the data in the registration can be used for running the event, e.g. make a name tag, count me as participant. We acknowledge that the data are public on github.
- [x] We agree that photos and videos might be taken and published (e.g. on social media) during the event.
- [x] We understand that we might NOT get a T-Shirt, because they might be in production already

Are you from a sponsoring company?
- [ ] Yes, I am from company ?????

### CODE REVIEW

**Comment by jonaslorenz** [comment]
Why is this marked as "Some checks haven’t completed yet"? If I click on "details" for the CI job it looks very much "passed" and finished ("ran for 33 seconds" "a day ago") to me.

**Comment by wolframkriesing** [comment]
hi @jonaslorenz i restarted the test run, lets see if it results in all-green :)
it would be great if your colleague who you are registering for too could also give a short message that he agrees to all things in the checkboxes too, that would be nice, thanks

**Comment by DanGlsmn** [comment]
@wolframkriesing @jonaslorenz I hereby also agree to the terms in the checkboxes. Looking forward to the event!

**Comment by wolframkriesing** [comment]
@DanGlsmn and @jonaslorenz thanks a lot for responding and checking all things, looking fwd to see you at the event. merging it now

**Comment by jonaslorenz** [comment]
@wolframkriesing thanks a lot, see you there!

**Pull request merged**
