### PR TITLE
registration of daniel weiß 🥳

### PR DESCRIPTION
**Pull request by WanielDeiss**
I would like to register for JS CraftCamp.    
- [ X ] My pull request contains a JSON file `$firstname_$lastname.json` or `$nickname.json`    
- [ X ] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [ X ] If I can't attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ X ] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
- [ X ] I agree that photos and videos might be taken and published (e.g. on social media) during the event.

### CODE REVIEW

**Comment by lowsky** [comment]
Welcome, Daniel!
Can you please have a look into your pull request:
- Plz, change the entry of 'allergies' - it must be a string.
By running `npm test` you can check if the json is valid.

' looking forward to meet you a the unconf and talk about `cypress` !

**Comment by lowsky** [comment]
Welcome @DanielHilpoltsteiner ! CU you at the unconf.

**Comment by WanielDeiss** [comment]
hmmm i'm daniel weiß 🧐

**Comment by lowsky** [comment]
Sorry, sure, Waniel ;-) Pardon, @WanielDeiss ! Syntax completion screwed me ;-)

**Comment by lowsky** [comment]
@WanielDeiss would you like to officially sponsor the event or just bring some energy drinks along?

**Comment by WanielDeiss** [comment]
what did you mean with officially? :D

**Pull request merged**
