### PR TITLE
Add myself as a participant 2024

### PR DESCRIPTION
**Pull request by HeeL**
I would like to register for JS CraftCamp.

- [x] My pull request contains a JSON file `$name_or_nickname.json`
- [x] I read the `THE IMPORTANT STUFF` at [https://jscraftcamp.org/registration](https://jscraftcamp.org/registration), the JSON file follows the [template](https://github.com/jscraftcamp/website/blob/main/participants/_template.json), and contains the mandatory fields like `realName`, `githubAccountName`, `when`, `iCanTakeNotesDuringSessions`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`.
- [x] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on GitHub and I agree that I will be listed on the JSCraftCamp website as a participant.
- [x] I agree that photos and videos might be taken and published (e.g. on social media) during the event.
- [x] I understand that I might NOT get a T-Shirt, because they might be in production already
- [x] I asked my company about sponsoring (see open items at: https://github.com/orgs/jscraftcamp/projects/5/views/1)

### CODE REVIEW

**Comment by Narigo** [comment]
Hi @HeeL, I'd like to merge your registration, but I was wondering whether you wanted to add your company to your PR as well, since you mentioned sharing "our" experiences.

Also, I guess I need to ask about tweet-of-god repository once we meet onsite 😅

**Comment by HeeL** [comment]
@Narigo hey, thanks for the quick reply and for the interesting talk on JS Meetup last week. Let's leave merge it like this if its ok, I've just skipped some optional fields when filling up the json

**Comment by Narigo** [comment]
Thanks! Sure we can merge it, looking forward to meeting you at the JSCC24!

**Comment by Narigo** [comment]
@HeeL sorry, I haven't noticed you had an underscore in front of the JSON, which we shouldn't have allowed in the first place. Our automated check didn't test your PR and after removing the underscore, the check failed because of the missing field `githubAccountName`. Please see https://github.com/jscraftcamp/website/pull/1953 and its log at https://github.com/jscraftcamp/website/actions/runs/8869852950/job/24350974069

I'm going to add `"githubAccountName": "HeeL",` after the `realName` field. If you want this to be different or have objections, please let me know - best place to comment would be in the PR fixing the underscores that I mentioned before (https://github.com/jscraftcamp/website/pull/1953)

**Comment by HeeL** [comment]
Looks good, many thanks 👍

**Pull request merged**
