### PR TITLE
fix pull request template

### PR DESCRIPTION
**Pull request by jonaslorenz**
* removed allegedly compulsory field "what_can_i_contribute" that is not compulsory according to
tests
* removed some surplus spaces

### CODE REVIEW

**Comment by haslers** [comment]
We would still like to know what you can contribute, even if we don't have unit tests reflecting this. 

Do you maybe want to adapt the unit tests to cover that case?

**Comment by jonaslorenz** [comment]
http://jscraftcamp.org/registration.html also says it is not compulsory

**Comment by jonaslorenz** [comment]
fixed

**Comment by jonaslorenz** [comment]
oops, wrong button...

**Comment by andys8** [comment]
Appreciate the changes :+1:  (https://github.com/jscraftcamp/website/pull/273#issuecomment-310440421)

**Comment by davelosert** [comment]
@jonaslorenz : Sorry for the late feedback here & thanks again for the work!

Just wanted to give you a heads up why it is taking so long: 
We initially didn't want to make the field as a required one as we feared it would scare away some potential participants that may think they have nothing to share (maybe because of lack of experience or insecurities). 

On the other hand, we strongly believe that *everybody* can contribute - be it someone who just started out with JavaScript as well as the person working with it from the start.

So while the field is not _mandatory_, we still ask for it in every PR as an opportunity to get in contact and explain what an unconference is about and to encourage those who are insecure.

Is that understandable?

I will let you know as soon as we reached a decision :)

**Comment by marcoemrich** [comment]
legacy from last year :)

**Pull request closed without merging**
