### PR TITLE
Dimitry Polivaev

### PR DESCRIPTION
**Pull request by dpolivaev**
I would like to register for JS CraftCamp.    
- [X] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [X] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` 
- [X] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org

### CODE REVIEW

**Comment by cko** [comment]
We are booked out for saturday for now. You can either modify your registration and just participate on sunday or wait until next tuesday. We will probably add some more seats then.

**Comment by dpolivaev** [comment]
How is it going with my request?

**Comment by cko** [comment]
Could you add some more details?

**Comment by dpolivaev** [comment]
Which details are you missing?
Have you got a seat for me?

**Comment by wolframkriesing** [comment]
some infos in `what_can_i_contribute` would be awesome. And yeeees, there are seats, you are in front of the row :)

**Comment by dpolivaev** [comment]
Answered

**Pull request merged**
