### PR TITLE
feat: Add schedule for Friday

### PR DESCRIPTION
**Pull request by Narigo**
Not really styled, but at least you can see it...

### CODE REVIEW

**Comment by lowsky** [comment]
LPGTM - styling could be added later - and will be reusable next year 👍

**Review by lowsky — APPROVED** [review]
Amazing!

This is for Friday - could we get on for Saturday, too?
Would be nice - as it could show it as a reference or
to make some 🥁 - next year, if we like.
@Narigo WDYT?

**Comment by Narigo** [comment]
Yes, I didn't get around to do this during the event like I did for Friday.
We need a better / quicker system to create these schedules next time

lowsky ***@***.***> schrieb am Mi., 26. Juli 2023, 23:45:

**Comment by lowsky** [comment]
This was not used, finally, so I will close this PR now.

**Pull request closed without merging**
