### PR TITLE
WIP: Registration 2024

### PR DESCRIPTION
**Pull request by meldron**

### CODE REVIEW

**Comment by Narigo** [comment]
@meldron I've pushed more stuff and fixed stats. I changed Twitter with `X`. I didn't like having just `x` as a lowercase variable name in the JSON, so I used `X` instead... hope that doesn't cause any issues... 😬

Please have a look if you see something!

**Review by Narigo — APPROVED** [review]
Approved from what @meldron has done. Please someone review my changes as well ;)

**Comment by meldron** [comment]
Thanks a lot for finishing it!

**Comment by Narigo** [comment]
I think we missed removing a test file here for `_philip-lenhart.json` which seems to be an old registration. I don't see this person in this years registrations and it looks like the file was added with this PR. I'm going to remove it with PR #1953

**Pull request merged**
