### PR TITLE
Added _template-Json again as it was (accidently?) deleted

### PR DESCRIPTION
**Pull request by davelosert**
@cko : Is there a reason you deleted the _template.json after @wolframkriesing added it?
If so: It's still linked within the PR-Template - we should either add it again with this PR or delete the Link from the PR-Template.

### CODE REVIEW

**Comment by seelmann** [comment]
@davelosert please also apply the following patch to filter out the template from being rendered on the participants page:

```
diff --git a/scripts/concat-json.js b/scripts/concat-json.js
index 42f8ec2..1ded610 100644
--- a/scripts/concat-json.js
+++ b/scripts/concat-json.js
@@ -10,7 +10,7 @@ var destfile = args[1];
 var array = [];
 recursiveReaddirSync(srcdir)
   .filter(file => file.endsWith(".json"))
-  .filter(file => file != "_template.json")
+  .filter(file => file != "participants/_template.json")
   .sort((a,b) => hashcode().value(a)%1000 - hashcode().value(b)%1000)
   .forEach(file => {
     var content = fs.readFileSync(file, "utf8");
```

**Comment by davelosert** [comment]
@seelmann : Good catch :+1: . Added it.

**Comment by wolframkriesing** [comment]
it was fixed already, see https://github.com/jscraftcamp/website/blob/master/test/participants.js#L10

**Comment by seelmann** [comment]
@wolframkriesing Well, there are two places where iteration over participants files happen: in `test/participants.js` and in `scripts/concat-json.js`, and it smells like code duplication. Not very craftsman like :-(

**Comment by wolframkriesing** [comment]
:) good point, didnt see it … thx for the hint

Saludos, Regards, Gruesse

Wolfram Kriesing
crafting away software

JSCraftCamp, Munich, 8th+9th October <http://jscraftcamp.org>

2016-08-31 22:51 GMT+02:00 Stefan Seelmann <notifications@github.com>:

**Comment by cko** [comment]
Sorry, just noticed the problem with the rendering, not that it was now included in the PR template. Thanks for fixing!

**Pull request merged**
