### PR TITLE
registration: Yaroslav Poliakov

### PR DESCRIPTION
**Pull request by altersign**
I would like to register for JS CraftCamp.

- [x] My pull request contains a JSON file `$name_or_nickname.json`
- [x] The JSON file follows the template at [https://github.com/jscraftcamp/website/blob/main/participants/\_template.json](https://jscraftcamp.org/register/) and contains the mandatory fields like `name`, `when`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`
- [x] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on GitHub and I agree that I will be listed on the JSCraftCamp website as a participant.
- [x] I agree that photos and videos might be taken and published (e.g. on social media) during the event.
- [x] I understand that I might NOT get a T-Shirt, because they might be in production already

### CODE REVIEW

**Comment by meldron** [comment]
Hi @altersign, Unfortunately all of our Friday slots are already taken. We would put you at the top of the waiting list. Would you come also only on Saturday if Friday no more place becomes free?

**Comment by altersign** [comment]
> Hi @altersign, Unfortunately all of our Friday slots are already taken. We would put you at the top of the waiting list. Would you come also only on Saturday if Friday no more place becomes free?

Hi @meldron, thank you for the update. I will come only on Saturday, but hopefully there will be a place on Friday as well.

**Comment by Narigo** [comment]
Hi @altersign , if you change your PR for Saturday only, I can merge you. I'll add a label "waitlist-friday" to your PR, so if someone else is cancelling their registration, we would like to add you for Friday as well. Would that work for you?

**Comment by Narigo** [comment]
If you want to make it even easier for all of us, you can create another PR and set `friday: true` so we can merge once someone cancels their registration 😅

**Pull request merged**
