### PR TITLE
Add aharter to the list of participants

### PR DESCRIPTION
**Pull request by aharter**
I would like to register for JS CraftCamp.    
- [x] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`
- [x] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org

### CODE REVIEW

**Comment by davelosert** [comment]
hi @aharter : There is nothing you could contribute? You deleted the field also from the commit-message template. For sure there is something you can share, talk or discuss? :)

**Comment by aharter** [comment]
Thanks for the feedback, @davelosert. I updated the pull request.
You shouldn't let people get away with those things so easily ;). Maybe you can set the `what_can_i_contribute`-field as mandatory.

**Comment by davelosert** [comment]
@aharter We don't - thats why we ask in the comments. :)
But yeah ,maybe we can write a test for it @cko @wolframkriesing what do you think?

@aharter Looking forward on seeing you in October!

**Comment by wolframkriesing** [comment]
I like that there is some virtual/real interaction

Am 08.09.2016 11:54 nachm. schrieb "David Losert" <notifications@github.com

**Pull request merged**
