### PR TITLE
T-Shirt design (in progress...)

### PR DESCRIPTION
**Pull request by wolframkriesing**
What do you think about those "designs" for the T-Shirt, frontside (rest to come)?
Participants white shirts and staff black. Simple and straight.

Participants shirts:
bildschirmfoto 2016-09-04 um 23 17 16

Staff:
bildschirmfoto 2016-09-04 um 23 16 59

### CODE REVIEW

**Comment by wolframkriesing** [comment]
why this? it just came about accidentally, but matches well with
- think outside of the box
- leave your comfort zone
- extend your horizon
- think different
- try the unusual, unexpected

**Comment by davelosert** [comment]
I like it. Very good work and kudos to you and your family! :+1: 

Just one little thing (but i would have to see it to judge):
Could you put an outline the shield with in it's respective color (on white shirts with black, on black shirts with white)? Just so the logo itself is seen "completely"? 

Also I'd like to hear everybodies opinion to my idea to put the Github user name (maybe in the form *github.com/davelosert* - I'd like the nerdiness within) on the Staff-Shirts.

**Comment by wolframkriesing** [comment]
I would like `@wolframkriesing` on the back, for me it's easy since that is my twitter and github username :)

**Comment by cko** [comment]
Thanks for picking up the task
I don't have an opinion on the T-Shirt design - beside having a different color for staff.
For the sticker if woul prefer it, if they are printed with the logo from the website/twitter account with or without the text below.

**Comment by marcoemrich** [comment]
+1
looks great!

**Comment by wolframkriesing** [comment]
@davelosert the best I can do are the following (since I am editing SVG manually :)) #likeProgrammers

bildschirmfoto 2016-09-17 um 19 24 39
bildschirmfoto 2016-09-17 um 19 24 23

**Comment by wolframkriesing** [comment]
or soccer style :)
bildschirmfoto 2016-09-17 um 19 26 45

**Comment by davelosert** [comment]
@wolframkriesing Haha soccer style is nice. But i think i like the initial one the most, still.
Until when do we want to have / do we need a decision here?

**Comment by wolframkriesing** [comment]
will order it start of next week

Saludos, Regards, Gruesse

Wolfram Kriesing
crafting away software

JSCraftCamp, Munich, 8th+9th October <http://jscraftcamp.org>

2016-09-18 11:08 GMT+02:00 David Losert <notifications@github.com>:

**Comment by marcoemrich** [comment]
+1 for soccer style :)

**Comment by lowsky** [comment]
After checking the prices for printing, and so on, we will need to have the final version tomorrow.

Currently I plan to have a JS CraftCamp print on the left sleeve, and the already prepared design for the logos on the back.
#still-needs-small-corrections.

**Comment by davelosert** [comment]
@wolframkriesing : Should we merge this? Or close? The T-Shirts are done I guess! :D

**Comment by davelosert** [comment]
I will merge this in as it actually was our design! :+1:

**Pull request merged**
