### PR TITLE
Add Carsten Lamm to participants

### PR DESCRIPTION
**Pull request by FQ400**
I would like to register for JS CraftCamp.    
- [x] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [x] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.

### CODE REVIEW

**Comment by marcoemrich** [comment]
Sadly, due to GDPR we dropped some data fields (including tags). Maybe you could elaborate a bit more in  "what_can_i_contribute".

**Comment by lowsky** [comment]
@FQ400 can you just move the info from the `tags` part into the `what..` field ?
Seems, we just need to fix our template here.
Thanks.

**Comment by FQ400** [comment]
Should I remove the `tags` completely or just empty the array?

**Comment by marcoemrich** [comment]
doesn't matter. I would suggest removing the tags completely...

**Comment by FQ400** [comment]
I updated my PR. @marcoemrich @lowsky

**Comment by lowsky** [comment]
Thx. Looking forward to meet you there.

**Pull request merged**
